movielens_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "../data/duckdb/movielens.duckdb"
      schema: dev
      threads: 4
    ci:
      type: duckdb
      path: "../data/duckdb/movielens.duckdb"
      schema: ci
      threads: 2
